import type { MatterDto } from '../../contracts';

/**
 * The v3 design mock's demo litigation matter (Anderson v. Meridian
 * Logistics), expressed in the v2 schema. Rendered only when the dashboard
 * has no team — a live team starts from its real (possibly empty) store.
 */
export const DEMO_MATTER: MatterDto = {
  id: 'demo-anderson',
  schemaVersion: 2,
  caption: 'Anderson v. Meridian Logistics, Inc.',
  status: 'Active',
  matterNumber: 'AM-2025-0148',
  client: 'Daniel Anderson',
  caseNumber: '24STCV18832',
  department: 'Dept. 32',
  currentStage: 'discovery',
  createdAt: '2025-03-12T09:14:00.000Z',
  updatedAt: '2026-07-29T16:42:00.000Z',
  coreFields: [
    { label: 'Matter name', value: 'Anderson v. Meridian Logistics, Inc.' },
    { label: 'Client', value: 'Daniel Anderson' },
    { label: 'Client ID', value: 'c9d2f8a1-…-41ab' },
    { label: 'Matter No.', value: 'AM-2025-0148' },
    { label: 'Case No.', value: '24STCV18832' },
    { label: 'Court', value: 'Los Angeles Superior Court' },
    { label: 'Department', value: 'Dept. 32' },
    { label: 'Court location', value: 'Stanley Mosk Courthouse' },
    { label: 'Judge', value: 'Hon. Maria Delgado' },
    { label: 'Court contact', value: '(213) 555-0132' },
    { label: 'Clerk', value: 'R. Okafor' },
    { label: 'Dept. rules', value: 'Standing order re: discovery conferences' },
    { label: 'Jurisdiction', value: 'California' },
    { label: 'Opened', value: 'Mar 12, 2025' },
    { label: 'Closed', value: '' },
    { label: 'Docs workspace', value: 'AM-2025-0148 / Case Files' },
  ],
  systemFields: [
    { label: 'Matter ID', value: '3f8a1c2e-7b4d-4e90-a1f3-6c2d5e8b9b7d' },
    { label: 'Control issue', value: 'CTL-0148' },
    { label: 'Next deadline', value: 'DL-2026-0071 (verified)' },
    { label: 'Created', value: '2025-03-12 09:14' },
    { label: 'Updated', value: '2026-07-29 16:42' },
  ],
  nextDeadline: { date: 'Aug 14, 2026', label: 'Opposition to Motion to Compel' },
  parties: [
    {
      id: 'pty-a',
      name: 'Daniel Anderson',
      role: 'Plaintiff · client',
      side: 'Our client',
      kind: 'Individual',
      contact: 'Daniel Anderson',
      phone: '(310) 555-0114',
      email: 'danderson@gmail.com',
      address: '2140 Rowena Ave, Los Angeles, CA 90039',
      notes: 'Prefers evening calls. Copy Rosa Anderson on scheduling.',
    },
    {
      id: 'pty-b',
      name: 'Rosa Anderson',
      role: 'Plaintiff',
      side: 'Our client',
      kind: 'Individual',
      contact: 'Rosa Anderson',
      phone: '(310) 555-0119',
      email: 'rosa.anderson@gmail.com',
      address: '2140 Rowena Ave, Los Angeles, CA 90039',
      notes: 'Intervenor; loss of consortium claim.',
    },
    {
      id: 'pty-c',
      name: 'Meridian Logistics, Inc.',
      role: 'Defendant · Cross-Complainant',
      side: 'Opposing',
      kind: 'Corporation',
      contact: 'Karen Ramos, VP Operations',
      phone: '(714) 555-0286',
      email: 'kramos@meridianlog.com',
      address: '1885 Warner Ave, Santa Ana, CA 92705',
      notes: 'Insured by Pacific Mutual; carrier rep attends mediation.',
    },
    {
      id: 'pty-d',
      name: 'Halvorsen Transport LLC',
      role: 'Defendant',
      side: 'Opposing',
      kind: 'LLC',
      contact: 'Erik Halvorsen, Managing Member',
      phone: '(562) 555-0341',
      email: 'erik@halvorsentransport.com',
      address: '710 E Anaheim St, Long Beach, CA 90813',
      notes: 'Subhauler on the incident route.',
    },
    {
      id: 'pty-e',
      name: 'Cortez Freight LLC',
      role: 'Cross-Defendant',
      side: 'Opposing',
      kind: 'LLC',
      contact: 'Miguel Cortez, Owner',
      phone: '(909) 555-0177',
      email: 'mcortez@cortezfreight.com',
      address: '4402 Mission Blvd, Ontario, CA 91762',
      notes: 'Disputes indemnity obligation under subhaul agreement.',
    },
  ],
  counsel: [
    {
      id: 'co-1',
      partyId: 'pty-a',
      name: 'Karen Lin',
      firm: 'Lin & Barrett LLP',
      role: 'Lead counsel',
      bar: 'CA 248117',
      phone: '(213) 555-0900',
      email: 'klin@linbarrett.com',
      address: '801 S Figueroa St, Suite 1200, Los Angeles, CA 90017',
      notes: 'Primary contact for all filings and service.',
    },
    {
      id: 'co-2',
      partyId: 'pty-a',
      name: 'Devon Ruiz',
      firm: 'Lin & Barrett LLP',
      role: 'Associate',
      bar: 'CA 331902',
      phone: '(213) 555-0912',
      email: 'druiz@linbarrett.com',
      address: '801 S Figueroa St, Suite 1200, Los Angeles, CA 90017',
      notes: 'Handles discovery correspondence.',
    },
    {
      id: 'co-3',
      partyId: 'pty-b',
      name: 'Karen Lin',
      firm: 'Lin & Barrett LLP',
      role: 'Lead counsel',
      bar: 'CA 248117',
      phone: '(213) 555-0900',
      email: 'klin@linbarrett.com',
      address: '801 S Figueroa St, Suite 1200, Los Angeles, CA 90017',
      notes: 'Same counsel as Daniel Anderson; no conflict waiver on file.',
    },
    {
      id: 'co-4',
      partyId: 'pty-c',
      name: 'Jordan Pratt',
      firm: 'Pratt Coyne & Diaz',
      role: 'Lead counsel',
      bar: 'CA 214560',
      phone: '(714) 555-0733',
      email: 'jpratt@prattcoyne.com',
      address: '2 Park Plaza, Suite 900, Irvine, CA 92614',
      notes: 'Accepts service by email per stipulation.',
    },
    {
      id: 'co-5',
      partyId: 'pty-c',
      name: 'Alicia Fenn',
      firm: 'Pratt Coyne & Diaz',
      role: 'Co-counsel',
      bar: 'CA 289044',
      phone: '(714) 555-0741',
      email: 'afenn@prattcoyne.com',
      address: '2 Park Plaza, Suite 900, Irvine, CA 92614',
      notes: 'Appears at discovery hearings.',
    },
    {
      id: 'co-6',
      partyId: 'pty-d',
      name: 'Priya Nandakumar',
      firm: 'Coastline Defense Group',
      role: 'Lead counsel',
      bar: 'CA 302881',
      phone: '(562) 555-0490',
      email: 'pnandakumar@coastlinedg.com',
      address: '400 Oceangate, Suite 700, Long Beach, CA 90802',
    },
    {
      id: 'co-7',
      partyId: 'pty-e',
      name: 'Samuel Oyelaran',
      firm: 'Oyelaran Law APC',
      role: 'Lead counsel',
      bar: 'CA 276330',
      phone: '(909) 555-0620',
      email: 'sam@oyelaranlaw.com',
      address: '3200 Inland Empire Blvd, Ontario, CA 91764',
      notes: 'Solo practitioner; prefers telephone meet and confer.',
    },
  ],
  stages: [
    { id: 'pleading', label: 'Pleading', dates: 'Mar – Jun 2025' },
    { id: 'discovery', label: 'Discovery', dates: 'Jul 2025 – present' },
    { id: 'trial', label: 'Trial', dates: 'Set for Feb 8, 2027' },
    { id: 'settlement', label: 'Settlement & Mediation', dates: 'Feb 2026 – present' },
    { id: 'post', label: 'Post-Judgment', dates: '—' },
  ],
  pleading: {
    records: [
      {
        id: 'pl-1',
        partyId: 'pty-a',
        type: 'First Amended Complaint',
        status: 'Operative',
        filed: 'May 19, 2025',
        served: 'May 21, 2025',
        responseDue: 'Jun 20, 2025',
        responseFiled: 'Jun 9, 2025',
        related: 'Supersedes Complaint (Mar 12, 2025)',
        amendmentDue: 'Jun 30, 2025 — passed',
        claims:
          'Breach of contract, breach of implied covenant, and negligence. Adds negligent hiring claim.',
        dir: '/Pleadings/First Amended Complaint',
      },
      {
        id: 'pl-2',
        partyId: 'pty-a',
        type: 'Complaint',
        status: 'Superseded',
        filed: 'Mar 12, 2025',
        served: 'Mar 18, 2025',
        responseDue: 'Apr 17, 2025',
        responseFiled: 'Apr 15, 2025',
        related: 'Superseded by First Amended Complaint',
        claims: 'Original two causes of action. Retained for procedural record.',
        dir: '/Pleadings/Complaint',
      },
      {
        id: 'pl-3',
        partyId: 'pty-b',
        type: 'Complaint in Intervention',
        status: 'Operative',
        filed: 'Jul 1, 2025',
        served: 'Jul 3, 2025',
        responseDue: 'Aug 1, 2025',
        responseFiled: 'Jul 29, 2025',
        claims: 'Loss of consortium arising from the same delivery incident.',
        dir: '/Pleadings/Complaint in Intervention',
      },
      {
        id: 'pl-4',
        partyId: 'pty-c',
        type: 'Answer to First Amended Complaint',
        status: 'Operative',
        filed: 'Jun 9, 2025',
        served: 'Jun 10, 2025',
        related: 'Responds to First Amended Complaint',
        claims:
          '14 affirmative defenses, including statute of limitations, comparative fault, and failure to mitigate damages.',
        dir: '/Pleadings/Answer to FAC',
      },
      {
        id: 'pl-5',
        partyId: 'pty-c',
        type: 'Cross-Complaint',
        status: 'Operative',
        filed: 'Aug 4, 2025',
        served: 'Aug 6, 2025',
        responseDue: 'Sep 8, 2025',
        responseFiled: 'Sep 8, 2025',
        claims:
          'Indemnity and contribution against Cortez Freight LLC arising from the same delivery incident.',
        dir: '/Pleadings/Cross-Complaint',
      },
      {
        id: 'pl-6',
        partyId: 'pty-e',
        type: 'Answer to Cross-Complaint',
        status: 'Filed',
        filed: 'Sep 22, 2025',
        served: 'Sep 23, 2025',
        related: 'Responds to Cross-Complaint (Aug 4, 2025)',
        claims: 'General denial; disputes indemnity obligation under the subhaul agreement.',
        dir: '/Pleadings/Answer to Cross-Complaint',
      },
    ],
  },
  discovery: {
    requests: [
      {
        id: 'rq-1',
        type: 'RFP',
        set: 'Set One — contracts & ESI',
        parties: 'Anderson → Meridian',
        issued: 'Aug 28, 2025',
        served: 'Sep 2, 2025',
        due: 'Oct 6, 2025',
        prodDue: 'Oct 20, 2025',
        status: 'Complete',
        dir: '/Discovery/RFP/Set One',
      },
      {
        id: 'rq-2',
        type: 'Form Interrogatories',
        set: 'Set One',
        parties: 'Meridian → Anderson',
        issued: 'Sep 11, 2025',
        served: 'Sep 15, 2025',
        due: 'Oct 17, 2025',
        status: 'Responded',
        dir: '/Discovery/Form Interrogatories/Set One',
      },
      {
        id: 'rq-3',
        type: 'Special Interrogatories',
        set: 'Set Two — damages',
        parties: 'Anderson → Meridian',
        issued: 'Mar 5, 2026',
        served: 'Mar 9, 2026',
        due: 'Apr 10, 2026',
        status: 'Disputed',
        dir: '/Discovery/Special Interrogatories/Set Two',
      },
      {
        id: 'rq-4',
        type: 'Deposition Notice',
        set: 'Meridian PMQ',
        parties: 'Anderson → Meridian',
        issued: 'Apr 17, 2026',
        served: 'Apr 21, 2026',
        due: 'May 19, 2026',
        status: 'Complete',
        dir: '/Discovery/Deposition Notice/Meridian PMQ',
      },
      {
        id: 'rq-5',
        type: 'RFA',
        set: 'Set One',
        parties: 'Meridian → Anderson',
        issued: 'May 22, 2026',
        served: 'May 28, 2026',
        due: 'Jun 29, 2026',
        status: 'Responded',
        dir: '/Discovery/RFA/Set One',
      },
    ],
    motions: [
      {
        id: 'mo-1',
        type: 'Motion to Compel Further Responses',
        outcome: 'Pending',
        movingParty: 'Anderson',
        request: 'Special Interrogatories — Set Two',
        reservation: 'Jun 20, 2026',
        filed: 'Jul 10, 2026',
        oppositionDue: 'Aug 14, 2026',
        replyDue: 'Aug 27, 2026',
        hearing: 'Sep 3, 2026 · Dept. 32',
        issues:
          'Seeks further responses to Nos. 12–24 re damages computation; privilege and burden objections at issue. Sanctions requested.',
        dir: '/Discovery/Motions/Motion to Compel',
      },
      {
        id: 'mo-2',
        type: 'Motion for Protective Order',
        outcome: 'Denied',
        movingParty: 'Meridian',
        request: 'RFP — Set One',
        reservation: 'Nov 3, 2025',
        filed: 'Nov 14, 2025',
        oppositionDue: 'Dec 1, 2025',
        replyDue: 'Dec 8, 2025',
        hearing: 'Dec 15, 2025',
        ruled: 'Dec 15, 2025',
        issues:
          'Sought to limit ESI custodians to three. Denied without prejudice; production ordered within 30 days.',
        dir: '/Discovery/Motions/Motion for Protective Order',
      },
    ],
    meetAndConfers: [
      {
        id: 'mc-1',
        date: 'Jun 3, 2026 · 2:00 PM',
        method: 'Videoconference',
        outcome: 'Unresolved',
        participants: 'K. Lin (Anderson) · J. Pratt (Meridian)',
        dispute:
          'Privilege and completeness objections re Special Interrogatories — Set Two, Nos. 12–24.',
        next: 'Next step: motion to compel. Reservation held Jun 20, 2026.',
      },
      {
        id: 'mc-2',
        date: 'Oct 8, 2025',
        method: 'Letter',
        outcome: 'Partially Resolved',
        participants: 'K. Lin (Anderson) · J. Pratt (Meridian)',
        dispute: 'ESI custodian scope and date range for RFP Set One.',
        next: 'Agreed to six custodians; date range unresolved and raised again at Dec 15 hearing.',
      },
    ],
    productions: [
      {
        id: 'pr-1',
        type: 'Initial',
        bates: 'MER000001–004212',
        date: 'Oct 14, 2025',
        party: 'Meridian',
        dir: '/Discovery/Productions/Initial',
      },
      {
        id: 'pr-2',
        type: 'Supplemental',
        bates: 'MER004213–005871',
        date: 'Jan 22, 2026',
        party: 'Meridian',
        dir: '/Discovery/Productions/Supplemental',
      },
      {
        id: 'pr-3',
        type: 'Privilege Log',
        bates: '48 entries',
        date: 'Jan 22, 2026',
        party: 'Meridian',
        dir: '/Discovery/Productions/Privilege Log',
      },
    ],
    depositions: [
      {
        id: 'dp-1',
        name: 'D. Anderson',
        taken: 'taken Apr 7, 2026',
        review: 'In Review',
        note: 'transcript received Apr 21',
        dir: '/Discovery/Depositions/D. Anderson',
      },
      {
        id: 'dp-2',
        name: 'Meridian PMQ (K. Ramos)',
        taken: 'taken May 19, 2026',
        review: 'Complete',
        note: 'errata due Aug 2, 2026',
        dir: '/Discovery/Depositions/Meridian PMQ',
      },
    ],
  },
  trial: {
    settings: [
      {
        id: 'ts-1',
        type: 'Jury Trial',
        setAt: 'Mar 4, 2026',
        trialDate: 'Feb 8, 2027',
        days: '7',
        venue: 'LASC Dept. 32 · Hon. M. Delgado',
        status: 'Set',
      },
      {
        id: 'ts-2',
        type: 'Jury Trial',
        setAt: 'Jul 22, 2025',
        trialDate: 'Sep 14, 2026',
        days: '7',
        venue: 'LASC Dept. 32 · Hon. M. Delgado',
        status: 'Continued',
      },
    ],
    continuances: [
      {
        id: 'cn-1',
        text: 'Requested by Meridian · Sep 14, 2026 → Feb 8, 2027 · granted Mar 4, 2026 · expert availability and outstanding written discovery',
      },
    ],
    pretrialDeadlines: [
      {
        id: 'pt-1',
        title: 'Witness & exhibit lists',
        due: 'Jan 15, 2027',
        source: 'LASC Rule 3.25',
        status: 'Not Started',
      },
      {
        id: 'pt-2',
        title: 'Final Status Conference',
        due: 'Jan 22, 2027',
        source: 'Court order',
        status: 'Not Started',
      },
      {
        id: 'pt-3',
        title: 'Motions in limine',
        due: 'Jan 22, 2027',
        source: 'Court order',
        status: 'Prepared',
      },
      {
        id: 'pt-4',
        title: 'Jury instructions & verdict forms',
        due: 'Jan 29, 2027',
        source: 'CCP §607a',
        status: 'Not Started',
      },
      {
        id: 'pt-5',
        title: 'Trial brief',
        due: 'Feb 1, 2027',
        source: 'Standing order',
        status: 'Not Started',
      },
    ],
    pretrialFilings: [
      {
        id: 'pf-1',
        title: 'Trial brief',
        party: 'Anderson',
        due: 'Feb 1, 2027',
        dir: '/Trial/Pretrial/Trial brief',
      },
      {
        id: 'pf-2',
        title: 'Witness list',
        party: 'Anderson',
        due: 'Jan 15, 2027',
        dir: '/Trial/Pretrial/Witness list',
      },
      {
        id: 'pf-3',
        title: 'Exhibit list',
        party: 'Anderson',
        due: 'Jan 15, 2027',
        dir: '/Trial/Pretrial/Exhibit list',
      },
      {
        id: 'pf-4',
        title: 'Joint statement of the case',
        party: 'Both',
        due: 'Jan 22, 2027',
        dir: '/Trial/Pretrial/Joint statement',
      },
    ],
    witnesses: [
      {
        id: 'wt-1',
        name: 'D. Anderson',
        role: 'Fact',
        party: 'Plaintiff',
        availability: 'Confirmed',
        topics: 'Contract negotiation, delivery failures, damages.',
        docs: 'Direct outline drafted · disclosed Jan 8, 2027',
      },
      {
        id: 'wt-2',
        name: 'K. Ramos',
        role: 'PMQ',
        party: 'Defendant',
        availability: 'Tentative',
        topics: 'Dispatch practices, driver assignment, ESI retention.',
        docs: 'Cross outline drafted · subpoena served Dec 2, 2026',
      },
      {
        id: 'wt-3',
        name: 'Dr. E. Chou',
        role: 'Expert',
        party: 'Plaintiff',
        availability: 'Confirmed',
        topics: 'Lost profits computation. Available Feb 8 – Feb 19, 2027.',
        docs: 'Report served Nov 14, 2026',
      },
    ],
    exhibits: [
      {
        id: 'ex-1',
        number: '101',
        title: 'Master Services Agreement',
        admission: 'Proposed',
        foundation: 'Established',
        objections: 'No objection anticipated',
        dir: '/Trial/Exhibits/101',
      },
      {
        id: 'ex-2',
        number: '102',
        title: 'Delivery logs 2024–2025',
        admission: 'Proposed',
        foundation: 'In Progress',
        objections: 'Hearsay; business-records foundation needed via PMQ',
        dir: '/Trial/Exhibits/102',
      },
      {
        id: 'ex-3',
        number: '201',
        title: 'Meridian operations manual',
        admission: 'Marked',
        foundation: 'Established',
        objections: 'Relevance objection reserved',
        dir: '/Trial/Exhibits/201',
      },
    ],
    motionsInLimine: [
      {
        id: 'ml-1',
        number: '1',
        issue: 'Exclude reference to prior unrelated litigation',
        party: 'Anderson',
        filed: 'Jan 20, 2027',
        hearing: 'Jan 22, 2027',
        outcome: 'Pending',
        dir: '/Trial/Motions in Limine/No. 1',
      },
      {
        id: 'ml-2',
        number: '2',
        issue: 'Exclude undisclosed damages evidence',
        party: 'Meridian',
        filed: 'Jan 20, 2027',
        hearing: 'Jan 22, 2027',
        outcome: 'Pending',
        dir: '/Trial/Motions in Limine/No. 2',
      },
      {
        id: 'ml-3',
        number: '3',
        issue: 'Limit expert testimony to disclosed opinions',
        party: 'Meridian',
        filed: 'Jan 20, 2027',
        hearing: 'Jan 22, 2027',
        outcome: 'Pending',
        dir: '/Trial/Motions in Limine/No. 3',
      },
    ],
  },
  settlement: {
    records: [
      {
        id: 'st-1',
        date: 'Jul 15, 2026',
        type: 'Counteroffer',
        parties: 'Meridian → Anderson',
        amount: '$310,000',
        outcome: 'Proposed',
        terms: 'Mutual release; payment in two installments; confidentiality',
        dir: '/Settlement/Counteroffer/Jul 15, 2026',
      },
      {
        id: 'st-2',
        date: 'Jun 2, 2026',
        type: 'Offer',
        parties: 'Meridian → Anderson',
        amount: '$225,000',
        outcome: 'Rejected',
        terms: 'Full release, dismissal with prejudice',
        dir: '/Settlement/Offer/Jun 2, 2026',
      },
      {
        id: 'st-3',
        date: 'Apr 10, 2026',
        type: 'Demand',
        parties: 'Anderson → Meridian',
        amount: '$640,000',
        outcome: 'Countered',
        terms: 'Payment within 30 days; no confidentiality',
        dir: '/Settlement/Demand/Apr 10, 2026',
      },
      {
        id: 'st-4',
        date: 'Feb 18, 2026',
        type: 'Demand',
        parties: 'Anderson → Meridian',
        amount: '$750,000',
        outcome: 'Expired',
        terms: 'CCP §998 offer; expired unaccepted',
        dir: '/Settlement/Demand/Feb 18, 2026',
      },
    ],
    mediations: [
      {
        id: 'md-1',
        when: 'Sep 24, 2026 · 9:30 AM',
        status: 'Scheduled',
        result: 'Pending',
        mediator: 'Hon. R. Vasquez (Ret.)',
        org: 'ADR Services, Inc.',
        contact: 'rvasquez@adrservices.com',
        method: 'In Person',
        location: '1900 Ave of the Stars, LA',
        participants: 'Both parties, Meridian carrier rep',
        deadline: 'Briefs due Sep 17, 2026',
        discussion: 'Pre-mediation positions exchanged. Carrier authority expected up to $400,000.',
        unresolved:
          'Damages computation for 2025 lost profits; scope of mutual release for Cortez Freight.',
        next: 'Serve mediation brief and updated damages model by Sep 17, 2026.',
        dir: '/Settlement/Mediation/Sep 24, 2026',
      },
      {
        id: 'md-2',
        when: 'Mar 26, 2026 · 10:00 AM',
        status: 'Completed',
        result: 'No Settlement',
        mediator: 'L. Whitfield, Esq.',
        org: 'Signature Resolution',
        contact: 'lwhitfield@sigres.com',
        method: 'Video',
        location: 'Zoom',
        participants: 'Both parties',
        amount: '$400,000',
        discussion: 'Gap of roughly $340,000 at close. Defense disputed lost-profits methodology.',
        unresolved: 'All monetary terms; parties agreed to revisit after PMQ deposition.',
        next: 'Revisit after written discovery closes — led to Sep 2026 session.',
        dir: '/Settlement/Mediation/Mar 26, 2026',
      },
    ],
  },
  postJudgment: {
    judgmentStatus: 'Not Entered',
    enforcementStatus: 'Not Started',
  },
  events: [
    {
      id: 'ev-manual-1',
      date: 'Mar 12, 2025',
      type: 'Filed',
      group: 'Core',
      description: 'Complaint filed in Los Angeles Superior Court; matter opened.',
      parties: 'Anderson',
      docs: 'Complaint',
      note: 'Assigned to Dept. 32, Hon. Maria Delgado.',
      sourceRef: 'Entered by K. Lin',
    },
  ],
};
